import { colors, shadows } from '@/theme/tokens';
import type { Theme } from './types';

export const darkTheme: Theme = {
  scheme: 'dark',
  colors: {
    background: colors.neutral[950],
    foreground: colors.neutral[50],
    card: colors.neutral[900],
    cardForeground: colors.neutral[50],
    popover: colors.neutral[900],
    popoverForeground: colors.neutral[50],
    primary: colors.pulse[400],
    primaryForeground: colors.neutral[950],
    secondary: colors.neutral[800],
    secondaryForeground: colors.neutral[50],
    muted: colors.neutral[800],
    mutedForeground: colors.neutral[400],
    accent: colors.pulse[900],
    accentForeground: colors.pulse[200],
    destructive: colors.error[500],
    destructiveForeground: colors.white,
    border: colors.neutral[800],
    input: colors.neutral[800],
    ring: colors.pulse[400],
    success: colors.success[500],
    warning: colors.warning[500],
    info: colors.info[500],
  },
  shadow: shadows,
};

export const darkThemeCssVars: Record<string, string> = {
  '--color-background': darkTheme.colors.background,
  '--color-foreground': darkTheme.colors.foreground,
  '--color-card': darkTheme.colors.card,
  '--color-card-foreground': darkTheme.colors.cardForeground,
  '--color-popover': darkTheme.colors.popover,
  '--color-popover-foreground': darkTheme.colors.popoverForeground,
  '--color-primary': darkTheme.colors.primary,
  '--color-primary-foreground': darkTheme.colors.primaryForeground,
  '--color-secondary': darkTheme.colors.secondary,
  '--color-secondary-foreground': darkTheme.colors.secondaryForeground,
  '--color-muted': darkTheme.colors.muted,
  '--color-muted-foreground': darkTheme.colors.mutedForeground,
  '--color-accent': darkTheme.colors.accent,
  '--color-accent-foreground': darkTheme.colors.accentForeground,
  '--color-destructive': darkTheme.colors.destructive,
  '--color-destructive-foreground': darkTheme.colors.destructiveForeground,
  '--color-border': darkTheme.colors.border,
  '--color-input': darkTheme.colors.input,
  '--color-ring': darkTheme.colors.ring,
  '--color-success': darkTheme.colors.success,
  '--color-warning': darkTheme.colors.warning,
  '--color-info': darkTheme.colors.info,
  '--radius-sm': '4px',
  '--radius-md': '8px',
  '--radius-lg': '12px',
  '--radius-xl': '16px',
  '--radius-2xl': '24px',
  '--radius-full': '9999px',
  '--spacing-xs': '4px',
  '--spacing-sm': '8px',
  '--spacing-md': '12px',
  '--spacing-lg': '16px',
  '--spacing-xl': '24px',
  '--spacing-2xl': '32px',
  '--spacing-3xl': '48px',
  '--font-sans': 'System',
  '--font-mono': 'Courier',
  '--font-size-display': '36px',
  '--font-size-h1': '30px',
  '--font-size-h2': '24px',
  '--font-size-h3': '20px',
  '--font-size-h4': '18px',
  '--font-size-body': '16px',
  '--font-size-caption': '14px',
  '--font-size-label': '12px',
  '--line-height-display': '44px',
  '--line-height-h1': '38px',
  '--line-height-h2': '32px',
  '--line-height-h3': '28px',
  '--line-height-h4': '26px',
  '--line-height-body': '24px',
  '--line-height-caption': '20px',
  '--line-height-label': '16px',
  '--shadow-sm': '0 1px 2px rgba(0,0,0,0.3)',
  '--shadow-md': '0 2px 4px rgba(0,0,0,0.4)',
  '--shadow-lg': '0 4px 8px rgba(0,0,0,0.5)',
  '--shadow-xl': '0 8px 16px rgba(0,0,0,0.6)',
};
