import { colors, shadows } from '@/theme/tokens';
import type { Theme } from './types';

export const lightTheme: Theme = {
  scheme: 'light',
  colors: {
    background: colors.neutral[0],
    foreground: colors.neutral[900],
    card: colors.neutral[0],
    cardForeground: colors.neutral[900],
    popover: colors.neutral[0],
    popoverForeground: colors.neutral[900],
    primary: colors.pulse[500],
    primaryForeground: colors.white,
    secondary: colors.neutral[100],
    secondaryForeground: colors.neutral[900],
    muted: colors.neutral[100],
    mutedForeground: colors.neutral[500],
    accent: colors.pulse[50],
    accentForeground: colors.pulse[700],
    destructive: colors.error[500],
    destructiveForeground: colors.white,
    border: colors.neutral[200],
    input: colors.neutral[200],
    ring: colors.pulse[500],
    success: colors.success[500],
    warning: colors.warning[500],
    info: colors.info[500],
  },
  shadow: shadows,
};

export const lightThemeCssVars: Record<string, string> = {
  '--color-background': lightTheme.colors.background,
  '--color-foreground': lightTheme.colors.foreground,
  '--color-card': lightTheme.colors.card,
  '--color-card-foreground': lightTheme.colors.cardForeground,
  '--color-popover': lightTheme.colors.popover,
  '--color-popover-foreground': lightTheme.colors.popoverForeground,
  '--color-primary': lightTheme.colors.primary,
  '--color-primary-foreground': lightTheme.colors.primaryForeground,
  '--color-secondary': lightTheme.colors.secondary,
  '--color-secondary-foreground': lightTheme.colors.secondaryForeground,
  '--color-muted': lightTheme.colors.muted,
  '--color-muted-foreground': lightTheme.colors.mutedForeground,
  '--color-accent': lightTheme.colors.accent,
  '--color-accent-foreground': lightTheme.colors.accentForeground,
  '--color-destructive': lightTheme.colors.destructive,
  '--color-destructive-foreground': lightTheme.colors.destructiveForeground,
  '--color-border': lightTheme.colors.border,
  '--color-input': lightTheme.colors.input,
  '--color-ring': lightTheme.colors.ring,
  '--color-success': lightTheme.colors.success,
  '--color-warning': lightTheme.colors.warning,
  '--color-info': lightTheme.colors.info,
  '--radius-sm': '4px',
  '--radius-md': '8px',
  '--radius-lg': '12px',
  '--radius-xl': '16px',
  '--radius-2xl': '24px',
  '--radius-full': '9999px',
  '--spacing-xs': '4px',
  '--spacing-sm': '8px',
  '--spacing-md': '12px',
  '--spacing-lg': '16px',
  '--spacing-xl': '24px',
  '--spacing-2xl': '32px',
  '--spacing-3xl': '48px',
  '--font-sans': 'System',
  '--font-mono': 'Courier',
  '--font-size-display': '36px',
  '--font-size-h1': '30px',
  '--font-size-h2': '24px',
  '--font-size-h3': '20px',
  '--font-size-h4': '18px',
  '--font-size-body': '16px',
  '--font-size-caption': '14px',
  '--font-size-label': '12px',
  '--line-height-display': '44px',
  '--line-height-h1': '38px',
  '--line-height-h2': '32px',
  '--line-height-h3': '28px',
  '--line-height-h4': '26px',
  '--line-height-body': '24px',
  '--line-height-caption': '20px',
  '--line-height-label': '16px',
  '--shadow-sm': '0 1px 2px rgba(0,0,0,0.05)',
  '--shadow-md': '0 2px 4px rgba(0,0,0,0.1)',
  '--shadow-lg': '0 4px 8px rgba(0,0,0,0.12)',
  '--shadow-xl': '0 8px 16px rgba(0,0,0,0.15)',
};
